### ISSUE TITLE
English sites

### ISSUE THREAD

**Issue by Dmnboruto** [CrazyXacker/anilabx#10]
English sites like for anime gogoanime zoro animixplay 9anime manga mangareader manga4life mangakakarot

Pls this app looks so amazing but no English sources

**Comment by CrazyXacker** [comment]
@Dmnboruto 
some of suggested catalogs already in app. see checklist

- [✓] MangaReader
- [✓] Manga4Life (MangaLife)
- [✓] MangaKakalot (and Mangakakalots)
- [ ] GogoAnime
- [ ] Zoro
- [ ] AniMoixPlay
- [ ] 9anime
