### ISSUE TITLE
when i try to read manga, it says "decoding failed". how do i fix that?

### ISSUE THREAD

**Issue by LegendaryXboi** [CrazyXacker/anilabx#2]
and can you also add MangaDex as an English source?

**Comment by CrazyXacker** [comment]
> and can you also add MangaDex as an English source?

What type of manga reader do you use? What manga/chapter from what catalog causes this issue?
MangaDex will be added later.

**Comment by LegendaryXboi** [comment]
i was using mangapark.

**Comment by CrazyXacker** [comment]
> i was using mangapark.

this is not all the information I asked for

**Comment by LegendaryXboi** [comment]
what do you mean by "manga reader" is it like a repository?. and as for the manga i tried it with attack on titan.

**Comment by LegendaryXboi** [comment]
is it in the services part of the catalogs?

**Comment by CrazyXacker** [comment]
> what do you mean by "manga reader", is it like a catalog? and as for the manga i tried it with attack on titan.

App has two different manga readers: GPU and System. You can change it in Settings -> Manga reader - Manga reader type
GPU reader uses OpenGL for picture rendering and provide much more output quality picture but may throw "Decoding failded" error if source picture has errors.
System reader more stable and can even proceed pictures with errors but has little bit worse output picture quality (you may not even notice it)
So, try change manga reader to System and check if error persist. If not - use that type of reader for MangaPark

**Comment by LegendaryXboi** [comment]
okay thx
