### ISSUE TITLE
Italian Source for manga

### ISSUE THREAD

**Issue by kinglolloman90** [CrazyXacker/anilabx#3]
Is it possible to add [https://www.mangaeden.com/it/](url) to the source for manga? This app is awesome guys, but I'd like to read manga in my mother language. I know that there was a parser for this site on the old mangawatcherx app, maybe it could be used as a starting point to implementing this one?

Thanks for you attention and your job!

**Comment by CrazyXacker** [comment]
> Is it possible to add [https://www.mangaeden.com/it/](url) to the source for manga? This app is awesome guys, but I'd like to read manga in my mother language. I know that there was a parser for this site on the old mangawatcherx app, maybe it could be used as a starting point to implementing this one?
> 
> Thanks for you attention and your job!

Hi. I can add it now, but in AniLabX it will have some issues (no covers in catalog). I wan't use official API from MangaEden, but it needs some time to implement. Maybe in next release it will be available.

**Comment by kinglolloman90** [comment]
> > Is it possible to add [https://www.mangaeden.com/it/](url) to the source for manga? This app is awesome guys, but I'd like to read manga in my mother language. I know that there was a parser for this site on the old mangawatcherx app, maybe it could be used as a starting point to implementing this one?
> > Thanks for you attention and your job!
> 
> Hi. I can add it now, but in AniLabX it will have some issues (no covers in catalog). I wan't use official API from MangaEden, but it needs some time to implement. Maybe in next release it will be available.

Thanks for the reply and sorry for my late response! If you could add managaeden IT, also with cover problem, it will be awesome! A later fix 
for covers would be much appreaciated, but just have the chance to use anilabx with an italian source would be fantastic! Thank you!

**Comment by kinglolloman90** [comment]
> > Is it possible to add [https://www.mangaeden.com/it/](url) to the source for manga? This app is awesome guys, but I'd like to read manga in my mother language. I know that there was a parser for this site on the old mangawatcherx app, maybe it could be used as a starting point to implementing this one?
> > Thanks for you attention and your job!
> 
> Hi. I can add it now, but in AniLabX it will have some issues (no covers in catalog). I wan't use official API from MangaEden, but it needs some time to implement. Maybe in next release it will be available.

Is it possible to have an approximate date when managaeden will be added? If it will be added, of course :)
