### ISSUE TITLE
Firebase sync

### ISSUE THREAD

**Issue by Jamminroot** [CrazyXacker/anilabx#7]
Hey! Is it possible to implement firebase sync for user library?

**Comment by CrazyXacker** [comment]
@Jamminroot hi. Sorry for long answer. Can you provide link for documentation? I'll check it

**Comment by Jamminroot** [comment]
Depends on the app language. For flutter starting point would be something like
https://firebase.flutter.dev/docs/firestore/usage/
Can't find pub.dev library for it, but it's there for sure (not sure why I assumed that it's on flutter though :D)

And for android:
https://firebase.google.com/docs/firestore/quickstart
(Necessary links are somewhere in the documentation).

Implementation is fairly simple once you wrap your head around it - shouldn't be a problem to add (as far as I see from a user point of view), and all prerequisites are ready for that: 
- app already has auth flow with email
- collection of mangas\animes

So rough route would be something like:
- add user-specific collection in firebase (where each entry to specific collection is only accessible to user-id, which is deterministically evaluated upon auth
- just dump whole thing to firebase as serialized JSON lol :D 

Sorry if im going too far with suggestions. Thx for app anyway!
