### ISSUE TITLE
Can you add English Sources for Anime,Drama,Light novel

### ISSUE THREAD

**Issue by adarshkrbr** [CrazyXacker/anilabx#8]
I really like your app. Just one app for everything, amazing work!....If possible add english sources for each section
For anime you can use(gogoanime.pe,zoro.to, animixplay)
Light novel(wuxiaworld,wuxia.city,readwn.com)

**Comment by CrazyXacker** [comment]
@adarshkrbr thank you for list of sources. I'll try to add it into app

**Comment by adarshkrbr** [comment]
If you want more sources
English anime source here
https://piracy.moe/
For dramas, tv series in english : fmovies.to & sflix.to,vidembed.cc ...but these contain ads

**Comment by CrazyXacker** [comment]
@adarshkrbr thank you. i'll check it out
unfortunately, i won't add any catalog with movies/tv shows into app
